### ISSUE TITLE
Keep .gitignore when creating new projects

### ISSUE THREAD

**Issue by knowler** [enhance-dev/create#1]
The create script doesn’t seem to keep the `.gitignore` from the starter project. It does keep the `.npmignore` file, so I could just copy from there.

**Comment by d2s** [comment]
Noticed the similar problem. At the moment of writing, this means ~6878 extra files for a new Git repository (by default).

![2022-08-31-2203-enhance-gitignore-missing_7qwSFmVRHX](https://user-images.githubusercontent.com/135053/187762047-9d1969ba-9330-4eab-85ad-3f67206bdaec.png)

**Comment by ryanblock** [comment]
Happy to take a look at this but can you provide more specific repro steps?

**Comment by knowler** [comment]
This happened for me when I ran the command in the [quick start docs](https://enhance.dev/docs/):

```shell
npm create @enhance ./my-project -y
```

**Comment by ryanblock** [comment]
Ok, on it!

**Comment by ryanblock** [comment]
Ok, this should be fixed for the `npm create @enhance` workflow, please let me know if it's still giving you any trouble!
